markdown: kramdown

includes_dir: .

permalink: /blog/:month-:day-:year/:title/

# algolia_search:
#   api_key: ''
#   index_name: ''
# Uncomment this if you want to use Algolia’s search.
# It’s free for open-source projects.

exclude:
  - /**/.git/*
  - /_projects/**/_*_repo/*
  - /_projects/*/assets/css/*
  - /_projects/**/docs/*
  - .sass-cache/

unmarked_external_link_selectors:
  - .layout--home a
  - a[href*=travis]
  - a[href*=coverity]
  - a[href*=codecov]

landing_priority: [software, specs, blog]

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:month-:day-:year/:title/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec
